import type { ForPage } from "./types";

export const THREAT_PAGES: ForPage[] = [
  /* ─────────────────────────────────────────────────────
     DEEPFAKES
     ───────────────────────────────────────────────────── */
  {
    slug: "deepfakes",
    category: "threat",
    parentIndustry: "recruitment",
    title: "Certifyd for Deepfakes",
    metaTitle: "Deepfake Protection \u2014 Device-Bound Identity Verification",
    metaDescription:
      "Deepfakes can fool eyes and ears, but they can\u2019t fake a cryptographic passkey. Verify identity through device-bound authentication with Certifyd.",
    badge: "Deepfakes",
    headline: "You Can\u2019t Trust Your Eyes Anymore. Trust Cryptography Instead.",
    subtitle:
      "Deepfake technology can synthesise faces and voices in real time. Certifyd defeats deepfakes by verifying identity through device-bound cryptographic authentication \u2014 not through what you can see or hear.",
    heroGraphic: "qr-scan",
    heroCard: { name: "Sarah Mitchell", secondaryLabel: "Status", secondaryValue: "Verified via Certifyd" },
    searchIntentParagraph:
      "Deepfake protection with Certifyd works at the protocol level, not the perception level. Deepfake detection tools try to spot synthetic media \u2014 an arms race the detectors are losing. Certifyd takes a fundamentally different approach: instead of asking \u2018does this face look real?\u2019, it asks \u2018can this person complete a cryptographic challenge on their registered device?\u2019 A deepfake can synthesise any face and any voice, but it cannot possess the physical device that holds someone\u2019s passkey. Bi-directional, device-bound authentication makes deepfakes irrelevant to identity verification.",
    stats: [
      { value: "\u00a320M+", label: "lost in a single deepfake attack (Arup, 2024)" },
      { value: "3,000%", label: "increase in deepfake fraud attempts (2023\u20132024)" },
      { value: "30s", label: "to verify with Certifyd" },
    ],
    whyItMatters: [
      "In February 2024, engineering firm Arup lost over \u00a320 million after an employee was deceived by a deepfake video call that impersonated the company\u2019s CFO and other executives. The deepfakes were convincing enough to pass a live video conference. This was not a failure of training or awareness \u2014 the technology has simply surpassed the human ability to detect fakes.",
      "Deepfake fraud has exploded. Attempts increased by 3,000% between 2023 and 2024. AI-generated candidates are appearing in recruitment video interviews. Voice cloning can replicate a person\u2019s voice from a few seconds of audio. Real-time face-swapping tools are available for under \u00a3100. The tools that were science fiction five years ago are now consumer products.",
      "Deepfake detection is an arms race that defenders are losing. Every detection algorithm trains the next generation of generators to evade it. Certifyd takes a fundamentally different approach: it doesn\u2019t try to detect fakes. Instead, it proves authenticity through device-bound cryptographic authentication. A WebAuthn passkey is bound to a physical device \u2014 it cannot be cloned, transferred, or generated by AI. When someone verifies through Certifyd, they prove they possess the physical device registered to that identity. No video, no voice, no visual assessment \u2014 just cryptographic proof.",
    ],
    problems: [
      "Deepfake technology can synthesise faces and voices convincing enough to fool trained professionals.",
      "Deepfake detection tools are in an arms race with generation tools \u2014 and losing.",
      "Video calls, the standard for remote identity verification, are no longer trustworthy.",
      "AI-generated candidates, CEO fraud, and impersonation attacks are growing exponentially.",
    ],
    steps: [
      "Both parties open Certifyd on their registered devices \u2014 no video or voice needed",
      "Each person completes a cryptographic challenge through their device-bound passkey",
      "The system confirms both identities through WebAuthn authentication \u2014 unforgeable, unspoofable",
      "A tamper-proof record is created: who verified, when, and through which registered device",
    ],
    testimonial: {
      quote:
        "They created a voice model of his voice from public recordings. It sounded a bit like him, but knowing him well enough, I knew it wasn\u2019t him. Most people wouldn\u2019t.",
      attribution: "Cybersecurity professional, 20 years experience",
    },
    faqs: [
      {
        question: "How does Certifyd defeat deepfakes?",
        answer:
          "Certifyd doesn\u2019t try to detect deepfakes \u2014 it makes them irrelevant. Instead of analysing whether a face or voice is real (an arms race), Certifyd verifies identity through device-bound cryptographic authentication. The person proves they possess the physical device registered to their identity by completing a passkey challenge. A deepfake can generate any face or voice, but it cannot possess someone\u2019s physical phone. If the person can\u2019t complete the cryptographic challenge, they are not who they claim to be.",
      },
      {
        question: "What is device-bound authentication?",
        answer:
          "Device-bound authentication means the person\u2019s identity is tied to a specific physical device through WebAuthn passkeys. The private key is stored in the device\u2019s secure enclave (TPM chip or Secure Enclave) and never leaves the device. Authentication requires the physical device plus biometric or PIN unlock. This creates a chain of trust: the device proves the identity, and only the legitimate owner can unlock the device. No video, no voice, no screenshots \u2014 just hardware-backed cryptographic proof.",
      },
      {
        question: "Can\u2019t someone steal the device?",
        answer:
          "Possessing the device alone is not enough. The passkey requires the device owner\u2019s biometric authentication (fingerprint, face ID) or PIN to complete the cryptographic challenge. A stolen device without the owner\u2019s biometric is useless for verification. Additionally, devices can be remotely wiped and identities can be revoked through Certifyd\u2019s Organisation management. The security model is: something you have (the device) plus something you are (biometric) or something you know (PIN).",
      },
      {
        question: "Is this relevant for my business?",
        answer:
          "If your business conducts video calls, processes applications remotely, makes financial decisions based on verbal instructions, or employs people you haven\u2019t met in person \u2014 yes. Deepfake technology is democratising impersonation. The Arup attack cost \u00a320 million from a single video call. AI-generated candidates are appearing in recruitment pipelines. CEO fraud via voice cloning is targeting businesses of all sizes. Device-bound authentication is the only verification method that deepfakes cannot defeat.",
      },
    ],
    alsoRelevant: [
      { label: "Certifyd for CEO Fraud", slug: "ceo-fraud" },
      { label: "Certifyd for Voice Cloning", slug: "voice-cloning" },
      { label: "Certifyd for Remote Workers", slug: "remote-workers" },
    ],
    relatedSolutions: [
      { label: "Certify That Person", href: "/solutions/person/" },
      { label: "Certify That Business", href: "/solutions/business/" },
    ],
    relatedArticles: [
      { label: "The Arup Deepfake Attack: Lessons for Every Business", href: "/blog/arup-deepfake-attack/" },
      { label: "The Deepfake Playbook", href: "/blog/deepfake-playbook/" },
      { label: "Platform-Agnostic Verification", href: "/blog/platform-agnostic-verification/" },
    ],
    relatedResources: [
      {
        label: "NCSC \u2014 Deepfake Threats",
        href: "https://www.ncsc.gov.uk/",
        external: true,
      },
    ],
    ctaTitle: "Verify identity beyond what deepfakes can fake",
    ctaSecondaryLabel: "Read: The Arup Deepfake Attack",
    ctaSecondaryHref: "/blog/arup-deepfake-attack/",
  },

  /* ─────────────────────────────────────────────────────
     CEO FRAUD
     ───────────────────────────────────────────────────── */
  {
    slug: "ceo-fraud",
    category: "threat",
    parentIndustry: "workforce",
    title: "Certifyd for CEO Fraud",
    metaTitle: "CEO Fraud Protection \u2014 Verify Executive Identity",
    metaDescription:
      "CEO fraud costs UK businesses millions annually. Verify that instructions actually come from your CEO \u2014 not a deepfake or impersonator.",
    badge: "CEO Fraud",
    headline: "The CEO Just Called. Or Did They?",
    subtitle:
      "CEO fraud uses impersonation to authorise payments, access credentials, or sensitive actions. Certifyd lets teams verify that instructions genuinely come from the person claiming to send them.",
    heroGraphic: "qr-scan",
    heroCard: { name: "Catherine Moore", secondaryLabel: "Role", secondaryValue: "CFO, Sterling Group" },
    searchIntentParagraph:
      "CEO fraud protection with Certifyd replaces trust in voices, emails, and video calls with cryptographic verification. Traditional CEO fraud relies on impersonating a senior executive \u2014 via email, phone, or increasingly via deepfake video. Certifyd defeats this by requiring device-bound authentication: before acting on any high-stakes instruction, the recipient can request that the supposed sender verify their identity through their registered device. A deepfake can clone a CEO\u2019s voice and face, but it cannot complete a passkey challenge on the CEO\u2019s phone.",
    stats: [
      { value: "\u00a3245M", label: "UK CEO fraud losses (2023, Action Fraud)" },
      { value: "98%", label: "of attacks use email or phone impersonation" },
      { value: "30s", label: "to verify with Certifyd" },
    ],
    whyItMatters: [
      "CEO fraud \u2014 also known as business email compromise (BEC) or executive impersonation \u2014 costs UK businesses hundreds of millions annually. Action Fraud data shows losses of \u00a3245 million in 2023 alone. The attack vector is simple: a criminal impersonates a CEO, CFO, or other senior executive and instructs an employee to make an urgent payment, share credentials, or take some other high-stakes action.",
      "The sophistication of these attacks has escalated dramatically. What used to be a poorly worded email is now a convincing voice call using cloned audio, or a deepfake video conference call (as in the Arup case). Criminals research targets thoroughly: they know the CEO\u2019s communication style, their schedule, and their relationships. The urgency of the request (\u2018I\u2019m in an important meeting, can you quickly do this?\u2019) is designed to bypass verification procedures.",
      "Training and awareness help, but they fail against high-quality impersonation. Certifyd provides a protocol-level solution: any employee receiving a high-stakes instruction can request the sender to verify through Certifyd. The sender must complete a passkey challenge on their registered device. If they can\u2019t \u2014 because they\u2019re not the real person \u2014 the instruction is flagged immediately. This makes CEO fraud structurally impossible, not just unlikely.",
    ],
    problems: [
      "Deepfake voice and video calls can impersonate executives convincingly enough to authorise payments.",
      "Email impersonation bypasses technical controls through social engineering, not technical exploits.",
      "Employees are trained to be responsive to senior executives \u2014 urgency overrides verification instincts.",
      "Existing controls (callback procedures, dual authorisation) fail when the attacker can clone the executive\u2019s voice.",
    ],
    steps: [
      "Employee receives a high-stakes instruction from a supposed executive",
      "Employee requests the sender to verify through Certifyd \u2014 a 30-second device-bound authentication",
      "If the sender is genuine, they complete the passkey challenge on their registered device",
      "If they can\u2019t complete it, the instruction is flagged as potentially fraudulent \u2014 crisis averted",
    ],
    testimonial: {
      quote:
        "When we hire somebody new, we get phishing attempts to them almost immediately. It\u2019s always from the CEO saying \u2018I\u2019m in an important meeting, can you quickly do this?\u2019",
      attribution: "Head of Cybersecurity, healthcare tech",
    },
    faqs: [
      {
        question: "How does Certifyd prevent CEO fraud?",
        answer:
          "Certifyd creates a verification step for high-stakes instructions. When an employee receives an unusual request from a supposed executive, they can ask the sender to verify through Certifyd. The sender must complete a cryptographic challenge on their registered device \u2014 something only the real executive possesses. A deepfake or impersonator cannot complete this challenge. The verification takes 30 seconds and creates a tamper-proof record.",
      },
      {
        question: "Won\u2019t asking the CEO to verify seem disrespectful?",
        answer:
          "Quite the opposite. CEOs who are serious about security will appreciate a team that verifies before acting on high-stakes requests. The alternative \u2014 losing \u00a320 million to a deepfake because nobody wanted to question the boss \u2014 is far worse. Certifyd normalises verification as a professional standard, not a challenge to authority. Many organisations are making verification mandatory for payment authorisations above a threshold.",
      },
      {
        question: "What about email-only CEO fraud (no deepfake)?",
        answer:
          "Even traditional email-based CEO fraud is defeated by Certifyd verification. If an employee receives an email that appears to come from the CEO, requesting a verification step through Certifyd means the attacker must possess the CEO\u2019s physical device. Email spoofing, domain lookalikes, and compromised email accounts cannot complete a device-bound cryptographic challenge.",
      },
      {
        question: "Can Certifyd be integrated into payment approval workflows?",
        answer:
          "Yes. Certifyd verification can be incorporated into any high-stakes approval process. Before a payment is processed, the authoriser verifies through their device-bound passkey. This creates a tamper-proof record that the specific authorised person approved the specific transaction. It\u2019s not just a signature or a login \u2014 it\u2019s cryptographic proof that the real person, with the real device, authorised the action.",
      },
    ],
    alsoRelevant: [
      { label: "Certifyd for Deepfakes", slug: "deepfakes" },
      { label: "Certifyd for Phishing", slug: "phishing" },
      { label: "Certifyd for Voice Cloning", slug: "voice-cloning" },
    ],
    relatedSolutions: [
      { label: "Certify That Person", href: "/solutions/person/" },
      { label: "Certify That Business", href: "/solutions/business/" },
    ],
    relatedArticles: [
      { label: "The Arup Deepfake Attack: Lessons for Every Business", href: "/blog/arup-deepfake-attack/" },
      { label: "The Voice Cloning Threat", href: "/blog/voice-cloning-threat/" },
      { label: "The Deepfake Playbook", href: "/blog/deepfake-playbook/" },
    ],
    relatedResources: [
      {
        label: "Action Fraud \u2014 CEO Fraud",
        href: "https://www.actionfraud.police.uk/",
        external: true,
      },
    ],
    ctaTitle: "Protect your business from executive impersonation",
    ctaSecondaryLabel: "Read: The Arup Deepfake Attack",
    ctaSecondaryHref: "/blog/arup-deepfake-attack/",
  },

  /* ─────────────────────────────────────────────────────
     VOICE CLONING
     ───────────────────────────────────────────────────── */
  {
    slug: "voice-cloning",
    category: "threat",
    parentIndustry: "workforce",
    title: "Certifyd for Voice Cloning",
    metaTitle: "Voice Cloning Protection \u2014 Device-Bound Verification",
    metaDescription:
      "Voice cloning can replicate anyone\u2019s voice from seconds of audio. Verify identity through cryptographic proof, not through what you hear.",
    badge: "Voice Cloning",
    headline: "That\u2019s Their Voice. But It\u2019s Not Them.",
    subtitle:
      "Voice cloning technology can replicate a person\u2019s voice from a few seconds of audio. Certifyd verifies identity through cryptographic proof that voices cannot fake.",
    heroGraphic: "qr-scan",
    heroCard: { name: "James Richardson", secondaryLabel: "Role", secondaryValue: "Board Member" },
    searchIntentParagraph:
      "Voice cloning protection with Certifyd eliminates the voice channel as a trusted identity signal. AI voice cloning can now replicate any person\u2019s voice from a few seconds of recorded audio \u2014 enough to fool colleagues, family members, and bank voice-recognition systems. Certifyd replaces voice-based trust with device-bound cryptographic authentication. When identity matters, the person verifies through their registered device, not through their voice. A cloned voice cannot complete a passkey challenge.",
    stats: [
      { value: "3s", label: "of audio needed to clone a voice" },
      { value: "85%", label: "of people can\u2019t distinguish cloned voices" },
      { value: "30s", label: "to verify with Certifyd" },
    ],
    whyItMatters: [
      "Modern voice cloning requires as little as three seconds of audio to create a convincing replica of someone\u2019s voice. Public figures, executives, and anyone with a social media presence or podcast appearance has enough recorded audio online for their voice to be cloned. Research shows that 85% of people cannot reliably distinguish a cloned voice from the real thing.",
      "Voice has historically been treated as a trust signal. We recognise colleagues, family members, and business contacts by their voice. Phone calls are considered more trustworthy than emails because \u2018I spoke to them directly.\u2019 Banks use voice recognition for authentication. All of these trust assumptions are now compromised. A criminal with a \u00a3100 voice cloning tool and three seconds of a CEO\u2019s podcast appearance can generate any instruction in that CEO\u2019s voice.",
      "Certifyd solves this by removing voice from the trust equation entirely. Identity is verified through a device-bound cryptographic passkey, not through auditory recognition. When someone receives a suspicious call, they can request the caller to verify through Certifyd \u2014 a 30-second process that the real person can complete and an impersonator cannot. This transforms voice from a trusted channel into what it actually is: an easily spoofed medium.",
    ],
    problems: [
      "Voice cloning requires only seconds of audio \u2014 any public figure or executive is a potential target.",
      "Most people cannot distinguish cloned voices from real ones, including trained professionals.",
      "Voice has historically been treated as a trust signal for identity \u2014 that assumption is now broken.",
      "Bank voice recognition, phone-based authorisations, and verbal instructions are all vulnerable.",
    ],
    steps: [
      "Suspicious call or voice message is received from a supposed known person",
      "Recipient requests the caller to verify through Certifyd \u2014 no voice analysis needed",
      "The caller must complete a device-bound passkey challenge on their registered phone",
      "If they can\u2019t complete it, the call is flagged as a potential impersonation \u2014 regardless of how convincing the voice sounds",
    ],
    testimonial: {
      quote:
        "They created a voice model of his voice from public recordings. It sounded a bit like him, but knowing him well enough, I knew it wasn\u2019t him. Most people wouldn\u2019t.",
      attribution: "Cybersecurity professional, 20 years experience",
    },
    faqs: [
      {
        question: "How does voice cloning work?",
        answer:
          "Modern voice cloning uses AI to analyse a sample of someone\u2019s voice (as little as 3 seconds) and create a model that can generate any text in that voice. The output is convincing enough to fool family members, colleagues, and even voice-recognition software. Tools are commercially available for under \u00a3100, and open-source alternatives are free. Anyone with a recorded voice \u2014 from a podcast, social media, or conference talk \u2014 is a potential target.",
      },
      {
        question: "Why can\u2019t voice detection tools solve this?",
        answer:
          "Voice deepfake detection faces the same arms race as visual deepfake detection: every improvement in detection trains the next generation of cloning tools to evade it. Detection accuracy varies widely, and real-time detection during a live call is even less reliable. Certifyd takes a fundamentally different approach \u2014 it doesn\u2019t try to analyse the voice at all. It verifies the person through their physical device, making the voice irrelevant to the identity proof.",
      },
      {
        question: "Is this a real threat for ordinary businesses?",
        answer:
          "Yes. Voice cloning is no longer limited to state actors or sophisticated criminals. Consumer-grade tools are widely available, and the barrier to entry is a few seconds of audio. Any business where verbal instructions trigger actions \u2014 payment authorisations, access grants, information sharing \u2014 is at risk. The Arup deepfake attack, which combined voice and video cloning, cost over \u00a320 million. Smaller businesses have been targeted for five and six-figure sums.",
      },
      {
        question: "How does Certifyd integrate with phone communications?",
        answer:
          "Certifyd doesn\u2019t replace phone calls \u2014 it adds a verification step alongside them. When a call\u2019s authenticity matters, the recipient can ask the caller to verify through Certifyd (a quick passkey authentication on their phone). This can happen during the call or immediately after. The verification record confirms the caller\u2019s identity cryptographically, regardless of what their voice sounded like.",
      },
    ],
    alsoRelevant: [
      { label: "Certifyd for Deepfakes", slug: "deepfakes" },
      { label: "Certifyd for CEO Fraud", slug: "ceo-fraud" },
      { label: "Certifyd for Social Engineering", slug: "social-engineering" },
    ],
    relatedSolutions: [
      { label: "Certify That Person", href: "/solutions/person/" },
      { label: "Certify That Business", href: "/solutions/business/" },
    ],
    relatedArticles: [
      { label: "The Voice Cloning Threat", href: "/blog/voice-cloning-threat/" },
      { label: "The Arup Deepfake Attack", href: "/blog/arup-deepfake-attack/" },
      { label: "Platform-Agnostic Verification", href: "/blog/platform-agnostic-verification/" },
    ],
    relatedResources: [
      {
        label: "NCSC \u2014 Voice and Audio Threats",
        href: "https://www.ncsc.gov.uk/",
        external: true,
      },
    ],
    ctaTitle: "Verify identity beyond what voices can prove",
    ctaSecondaryLabel: "Read: The Voice Cloning Threat",
    ctaSecondaryHref: "/blog/voice-cloning-threat/",
  },

  /* ─────────────────────────────────────────────────────
     PHISHING
     ───────────────────────────────────────────────────── */
  {
    slug: "phishing",
    category: "threat",
    parentIndustry: "workforce",
    title: "Certifyd for Phishing",
    metaTitle: "Phishing Protection \u2014 Verify Who\u2019s Really Contacting You",
    metaDescription:
      "Phishing attacks impersonate trusted people and organisations. Verify the sender\u2019s identity cryptographically \u2014 in 30 seconds with Certifyd.",
    badge: "Phishing",
    headline: "The Email Looks Right. The Sender Isn\u2019t.",
    subtitle:
      "Phishing attacks impersonate colleagues, executives, and trusted organisations. Certifyd lets you verify the sender\u2019s actual identity before acting on any request.",
    heroGraphic: "qr-scan",
    heroCard: { name: "David Peters", secondaryLabel: "Role", secondaryValue: "IT Manager" },
    searchIntentParagraph:
      "Phishing protection with Certifyd adds cryptographic identity verification to communications where impersonation is the attack vector. Phishing succeeds because emails, messages, and calls can be made to appear to come from trusted sources. Certifyd doesn\u2019t try to detect phishing \u2014 it lets the recipient verify the sender\u2019s identity through device-bound authentication. Before acting on a suspicious request, the recipient asks the sender to complete a Certifyd verification. If they can\u2019t \u2014 because they\u2019re an impersonator \u2014 the attack fails.",
    stats: [
      { value: "83%", label: "of UK businesses experienced phishing in 2024" },
      { value: "\u00a34.4M", label: "average cost of a data breach (IBM, 2024)" },
      { value: "30s", label: "to verify with Certifyd" },
    ],
    whyItMatters: [
      "83% of UK businesses experienced a phishing attack in 2024. Phishing remains the most common cyber attack vector because it exploits trust, not technology. An email that appears to come from a colleague, a text from the CEO, a call from IT \u2014 all can be impersonated with enough sophistication. Phishing awareness training helps, but even trained employees click on well-crafted phishing emails at rates of 10\u201315%.",
      "AI has transformed phishing from a numbers game into a precision weapon. Large language models generate contextually appropriate emails that mirror the target\u2019s communication style. Spear phishing campaigns research their targets through LinkedIn and social media. When the phishing email references a real project, uses the right internal terminology, and arrives at a plausible time \u2014 even cautious employees can be deceived.",
      "Email security tools filter known phishing patterns, but novel attacks slip through. Certifyd provides a last line of defence: when an employee receives a suspicious request, they can verify the sender\u2019s identity through Certifyd before acting. The sender must complete a device-bound passkey challenge. A phisher impersonating a colleague cannot complete this challenge because they don\u2019t possess the colleague\u2019s device. Simple, fast, and unforgeable.",
    ],
    problems: [
      "Phishing emails have become indistinguishable from legitimate communications using AI.",
      "Even trained employees fall for well-crafted spear phishing \u2014 awareness training has diminishing returns.",
      "Email security tools catch known patterns but miss novel, targeted attacks.",
      "The cost of a successful phishing attack (\u00a34.4M average data breach) far exceeds the cost of prevention.",
    ],
    steps: [
      "Employee receives a suspicious email or message requesting action",
      "Employee asks the supposed sender to verify through Certifyd \u2014 a 30-second process",
      "The sender completes a device-bound passkey challenge on their registered phone",
      "If they can\u2019t complete it, the message is confirmed as phishing \u2014 before any damage is done",
    ],
    testimonial: {
      quote:
        "When we hire somebody new, we get phishing attempts to them almost immediately. It\u2019s always from the CEO saying \u2018I\u2019m in an important meeting, can you quickly do this?\u2019",
      attribution: "Head of Cybersecurity, healthcare tech",
    },
    faqs: [
      {
        question: "How is Certifyd different from email security tools?",
        answer:
          "Email security tools analyse emails for known phishing patterns \u2014 suspicious links, domain spoofing, attachment types. They\u2019re valuable but reactive: they catch attacks that match known patterns. Certifyd adds sender identity verification: instead of analysing the email, it verifies the person who claims to have sent it. The sender must complete a cryptographic challenge on their registered device. This is proactive and defeats novel attacks that email filters haven\u2019t seen before.",
      },
      {
        question: "Won\u2019t this slow down communication?",
        answer:
          "Certifyd verification takes 30 seconds and is only needed for suspicious or high-stakes communications. It\u2019s not intended for every email \u2014 it\u2019s a verification step for when something feels off or when the requested action has significant consequences. Think of it as a fire extinguisher: you don\u2019t use it every day, but when you need it, it prevents catastrophic damage.",
      },
      {
        question: "What about phone-based phishing (vishing)?",
        answer:
          "Voice phishing (vishing) is increasingly common, especially with voice cloning technology. Certifyd works across all channels: if someone calls claiming to be from IT, HR, or your bank, you can ask them to verify through Certifyd. The verification is device-bound, not channel-bound, so it works whether the impersonation attempt comes via email, phone, video call, or text message.",
      },
      {
        question: "Can Certifyd protect against internal threats?",
        answer:
          "Certifyd verifies identity, which is the foundation of access control and authorisation. If someone within your organisation attempts to impersonate a more senior colleague (to authorise a payment, access restricted data, or approve a request), Certifyd verification will either confirm or refute their claimed identity. It protects against both external phishing and internal impersonation.",
      },
    ],
    alsoRelevant: [
      { label: "Certifyd for CEO Fraud", slug: "ceo-fraud" },
      { label: "Certifyd for Social Engineering", slug: "social-engineering" },
      { label: "Certifyd for Deepfakes", slug: "deepfakes" },
    ],
    relatedSolutions: [
      { label: "Certify That Person", href: "/solutions/person/" },
      { label: "Certify That Business", href: "/solutions/business/" },
    ],
    relatedArticles: [
      { label: "The Deepfake Playbook", href: "/blog/deepfake-playbook/" },
      { label: "The Voice Cloning Threat", href: "/blog/voice-cloning-threat/" },
      { label: "Platform-Agnostic Verification", href: "/blog/platform-agnostic-verification/" },
    ],
    relatedResources: [
      {
        label: "NCSC \u2014 Phishing Guidance",
        href: "https://www.ncsc.gov.uk/collection/phishing-scams",
        external: true,
      },
    ],
    ctaTitle: "Verify before you act on any request",
    ctaSecondaryLabel: "Read: The Deepfake Playbook",
    ctaSecondaryHref: "/blog/deepfake-playbook/",
  },

  /* ─────────────────────────────────────────────────────
     ROMANCE SCAMS
     ───────────────────────────────────────────────────── */
  {
    slug: "romance-scams",
    category: "threat",
    parentIndustry: "trades",
    title: "Certifyd for Romance Scams",
    metaTitle: "Romance Scam Protection \u2014 Verify Who You\u2019re Talking To",
    metaDescription:
      "Romance scams cost UK victims \u00a331M+ annually. Verify that the person you\u2019re talking to is real \u2014 cryptographically, not just visually.",
    badge: "Romance Scams",
    headline: "You\u2019ve Talked for Months. You\u2019ve Never Met. Are They Real?",
    subtitle:
      "Romance scams use fake identities to build emotional connections and extract money. Certifyd lets you verify that the person on the other end is real \u2014 before you\u2019re in too deep.",
    heroGraphic: "qr-scan",
    heroCard: { name: "Emma Davis", secondaryLabel: "Status", secondaryValue: "Identity Verified" },
    searchIntentParagraph:
      "Romance scam protection with Certifyd provides cryptographic proof that the person you\u2019re communicating with is who they claim to be. Romance scammers create elaborate fake identities \u2014 stolen photos, fabricated backstories, and now AI-generated faces and voices. Certifyd verification doesn\u2019t analyse photos or voices. It requires the person to prove their identity through a device-bound passkey: a cryptographic challenge that only the real person can complete on their registered device. If someone won\u2019t or can\u2019t verify, that tells you everything you need to know.",
    stats: [
      { value: "\u00a331M+", label: "UK romance scam losses annually" },
      { value: "8,000+", label: "romance scam reports to Action Fraud yearly" },
      { value: "30s", label: "to verify with Certifyd" },
    ],
    whyItMatters: [
      "Romance scams cost UK victims over \u00a331 million annually, with over 8,000 reports to Action Fraud each year. The true figure is likely much higher \u2014 shame prevents many victims from reporting. Victims lose an average of \u00a39,000 each, with some cases exceeding \u00a3100,000. The emotional damage often exceeds the financial loss.",
      "AI has supercharged romance scams. Scammers now use AI-generated profile photos that don\u2019t appear in reverse image searches, chatbots that maintain convincing conversations around the clock, and deepfake video calls that allow a scammer to appear as anyone. The traditional red flags (\u2018they won\u2019t video call\u2019, \u2018their photos are stolen\u2019) are becoming unreliable as the technology improves.",
      "The fundamental vulnerability in romance scams is unverified identity. The victim believes they\u2019re talking to someone real because the conversation feels real. Certifyd provides a simple, non-confrontational way to request verification: \u2018I like you \u2014 let\u2019s both verify on Certifyd so we know we\u2019re both real.\u2019 If the other person can\u2019t or won\u2019t complete device-bound verification, the answer is clear \u2014 before money changes hands.",
    ],
    problems: [
      "AI-generated photos, voices, and even video calls make it impossible to verify identity visually.",
      "Scammers build emotional connections over weeks or months before requesting money.",
      "Victims are emotionally invested before they realise the identity is fake.",
      "Traditional red flags (won\u2019t video call, stolen photos) are becoming unreliable as AI improves.",
    ],
    steps: [
      "You ask the person you\u2019re talking to to verify on Certifyd \u2014 a simple, non-confrontational request",
      "Both of you open Certifyd and complete a device-bound passkey authentication",
      "If both identities are verified, you know you\u2019re talking to a real person with a verified identity",
      "If they can\u2019t or won\u2019t verify, that tells you everything \u2014 before you send money",
    ],
    faqs: [
      {
        question: "How does Certifyd help with romance scams?",
        answer:
          "Certifyd provides a way to verify that the person you\u2019re talking to online is real. By requesting mutual Certifyd verification early in an online relationship, you can confirm that the other person has a device-bound, cryptographic identity. A scammer using stolen photos, AI-generated personas, or deepfake video cannot complete this verification because they don\u2019t have a registered device linked to the identity they\u2019re claiming.",
      },
      {
        question: "Won\u2019t asking to verify seem suspicious or offensive?",
        answer:
          "In an era of pervasive online fraud, requesting identity verification is a reasonable and increasingly normal step. Framing it positively (\u2018Let\u2019s both verify so we know we\u2019re real\u2019) makes it mutual, not accusatory. A genuine person will understand and welcome the step. Someone who refuses or makes excuses is showing you exactly what you need to know.",
      },
      {
        question: "Can Certifyd detect AI-generated personas?",
        answer:
          "Certifyd doesn\u2019t analyse photos or voices to detect AI generation \u2014 that\u2019s an arms race. Instead, it requires the person to prove their identity through a physical device. An AI-generated persona doesn\u2019t have a physical device with a registered passkey. The verification either succeeds (real person, verified device) or it doesn\u2019t. No grey areas, no analysis, no guesswork.",
      },
      {
        question: "What about dating apps \u2014 could they integrate Certifyd?",
        answer:
          "Yes. Dating platforms could offer Certifyd verification as a trust signal on profiles. A verified badge backed by device-bound cryptographic authentication is fundamentally more trustworthy than photo verification (which deepfakes can defeat) or social media linking (which fake accounts can imitate). For platforms serious about user safety, Certifyd provides the strongest possible identity assurance.",
      },
    ],
    alsoRelevant: [
      { label: "Certifyd for Online Dating", slug: "online-dating" },
      { label: "Certifyd for Deepfakes", slug: "deepfakes" },
      { label: "Certifyd for Social Engineering", slug: "social-engineering" },
    ],
    relatedSolutions: [
      { label: "Certify That Person", href: "/solutions/person/" },
    ],
    relatedArticles: [
      { label: "The Deepfake Playbook", href: "/blog/deepfake-playbook/" },
      { label: "Two-Way Verification Explained", href: "/blog/two-way-verification-explained/" },
      { label: "The Trust Layer That\u2019s Missing", href: "/blog/trust-layer-missing/" },
    ],
    relatedResources: [
      {
        label: "Action Fraud \u2014 Romance Scams",
        href: "https://www.actionfraud.police.uk/a-z-of-fraud/dating-fraud",
        external: true,
      },
    ],
    ctaTitle: "Verify the person, not just the profile",
    ctaSecondaryLabel: "Read: The Trust Layer That\u2019s Missing",
    ctaSecondaryHref: "/blog/trust-layer-missing/",
  },

  /* ─────────────────────────────────────────────────────
     SOCIAL ENGINEERING
     ───────────────────────────────────────────────────── */
  {
    slug: "social-engineering",
    category: "threat",
    parentIndustry: "workforce",
    title: "Certifyd for Social Engineering",
    metaTitle: "Social Engineering Protection \u2014 Verify Identity First",
    metaDescription:
      "Social engineering exploits trust in people, not flaws in technology. Verify the person behind the request with device-bound authentication.",
    badge: "Social Engineering",
    headline: "The Attack Doesn\u2019t Target Your Systems. It Targets Your People.",
    subtitle:
      "Social engineering attacks exploit human trust, not technical vulnerabilities. Certifyd provides a protocol for verifying the identity of anyone making a request \u2014 before trust is exploited.",
    heroGraphic: "qr-scan",
    heroCard: { name: "Michael Brooks", secondaryLabel: "Role", secondaryValue: "Security Director" },
    searchIntentParagraph:
      "Social engineering protection with Certifyd addresses the fundamental vulnerability in all social engineering attacks: unverified identity. Whether the attacker impersonates a colleague, a vendor, IT support, or a bank official, the attack depends on the target trusting the attacker\u2019s claimed identity. Certifyd provides a universal verification step: before acting on any request, the target can ask the requester to verify through device-bound cryptographic authentication. This transforms social engineering from a human judgement problem into a protocol problem \u2014 and protocols don\u2019t get fooled.",
    stats: [
      { value: "98%", label: "of cyber attacks involve social engineering" },
      { value: "\u00a34.4M", label: "average cost of a social engineering breach" },
      { value: "30s", label: "to verify with Certifyd" },
    ],
    whyItMatters: [
      "98% of cyber attacks involve some form of social engineering. Not because social engineering is sophisticated, but because it\u2019s reliable. Technical defences have improved dramatically \u2014 firewalls, encryption, multi-factor authentication. Social engineering bypasses all of them by targeting the human, not the system. An attacker who convinces an employee to share credentials doesn\u2019t need to crack the encryption.",
      "AI has made social engineering dramatically more effective. Attackers use large language models to craft contextually appropriate messages, voice cloning to impersonate known contacts, and deepfakes to conduct convincing video calls. The \u2018human firewall\u2019 approach \u2014 training employees to spot social engineering \u2014 is failing against AI-enhanced attacks because the attacks no longer exhibit the traditional red flags.",
      "Certifyd addresses social engineering at the protocol level, not the perception level. Instead of training people to spot fakes (a losing battle), Certifyd provides a verification step that cannot be circumvented by social manipulation. When someone requests action, the target asks them to verify through their device-bound passkey. A social engineer cannot complete this challenge because they don\u2019t possess the impersonated person\u2019s physical device. Simple, fast, and unforgeable.",
    ],
    problems: [
      "Social engineering bypasses every technical security control by targeting humans directly.",
      "AI-enhanced attacks are too sophisticated for awareness training to reliably detect.",
      "Impersonation of colleagues, executives, and trusted vendors exploits organisational trust.",
      "The \u2018human firewall\u2019 approach fails when attackers can perfectly mimic the people employees trust.",
    ],
    steps: [
      "Employee receives a request from someone claiming to be a colleague, vendor, or authority figure",
      "Employee asks the requester to verify through Certifyd \u2014 a 30-second device-bound authentication",
      "The requester must complete a passkey challenge on their registered device",
      "If they can\u2019t complete it, the request is flagged as social engineering \u2014 before any action is taken",
    ],
    testimonial: {
      quote:
        "They created a voice model of his voice from public recordings. It sounded a bit like him, but knowing him well enough, I knew it wasn\u2019t him. Most people wouldn\u2019t.",
      attribution: "Cybersecurity professional, 20 years experience",
    },
    faqs: [
      {
        question: "Why can\u2019t training alone stop social engineering?",
        answer:
          "Training improves awareness, but even trained employees fall for well-crafted social engineering 10\u201315% of the time. AI has raised the quality of attacks beyond what human perception can reliably detect. Voice cloning, deepfake video, and contextually perfect emails eliminate the traditional red flags that training teaches people to spot. The solution isn\u2019t better training \u2014 it\u2019s a protocol that removes the need for human judgement about identity.",
      },
      {
        question: "How does Certifyd change the social engineering dynamic?",
        answer:
          "Social engineering works because the attacker controls the narrative: they choose who to impersonate, what to request, and how to create urgency. Certifyd shifts control to the target. By requesting device-bound verification, the target introduces a step the attacker cannot fake. The attacker\u2019s narrative, persuasion skills, and AI tools become irrelevant \u2014 they either have the real person\u2019s device or they don\u2019t. It turns social engineering from a human judgement problem into a binary verification outcome.",
      },
      {
        question: "What about physical social engineering (tailgating, impersonation)?",
        answer:
          "Certifyd works for in-person social engineering too. If someone claims to be a vendor, IT engineer, or auditor and requests physical access, the site manager can ask them to verify through Certifyd. The person must prove their identity and organisational membership through their device-bound passkey. Someone who tailgated through a secure entrance or is impersonating a vendor cannot complete this verification.",
      },
      {
        question: "Can Certifyd protect against supply chain social engineering?",
        answer:
          "Yes. Supply chain attacks often involve impersonating a vendor to gain access or redirect payments. If a \u2018vendor\u2019 contacts you requesting a change to payment details or access credentials, requesting Certifyd verification confirms whether they are genuinely from the vendor organisation. Their device-bound identity is linked to their active organisational membership \u2014 an impersonator from outside the organisation cannot complete the verification.",
      },
    ],
    alsoRelevant: [
      { label: "Certifyd for Phishing", slug: "phishing" },
      { label: "Certifyd for CEO Fraud", slug: "ceo-fraud" },
      { label: "Certifyd for Deepfakes", slug: "deepfakes" },
    ],
    relatedSolutions: [
      { label: "Certify That Person", href: "/solutions/person/" },
      { label: "Certify That Business", href: "/solutions/business/" },
    ],
    relatedArticles: [
      { label: "The Deepfake Playbook", href: "/blog/deepfake-playbook/" },
      { label: "The Arup Deepfake Attack", href: "/blog/arup-deepfake-attack/" },
      { label: "The Voice Cloning Threat", href: "/blog/voice-cloning-threat/" },
    ],
    relatedResources: [
      {
        label: "NCSC \u2014 Social Engineering Guidance",
        href: "https://www.ncsc.gov.uk/collection/social-engineering",
        external: true,
      },
    ],
    ctaTitle: "Protect your team from identity-based attacks",
    ctaSecondaryLabel: "Read: The Deepfake Playbook",
    ctaSecondaryHref: "/blog/deepfake-playbook/",
  },
];
