export function initializeConnected(root){const controller=new AbortController();
const dialog=root.querySelector('#screen-dialog');let opener;
for(const button of root.querySelectorAll('[data-open-screen]'))button.addEventListener('click',()=>{opener=button;dialog.showModal()});
root.querySelector('[data-close]')?.addEventListener('click',()=>dialog.close());dialog?.addEventListener('close',()=>opener?.focus());
const states={added:{label:'On record',date:'30 Nov 2026',action:'The evidence and its expiry date are recorded together.',history:'Jamie’s manual handling certificate has been added for your team to review.'},due:{label:'Renewal approaching',date:'30 Nov 2026',action:'Arrange renewal before the recorded expiry date.',history:'The existing evidence remains attached to Jamie’s record.'},renewed:{label:'Renewed',date:'30 Nov 2027',action:'Replacement evidence reviewed. The next expiry date is recorded.',history:'The earlier evidence and review activity remain part of the history.'}};
for(const button of root.querySelectorAll('[data-record]'))button.addEventListener('click',()=>{const state=states[button.dataset.record];for(const other of root.querySelectorAll('[data-record]'))other.setAttribute('aria-pressed',String(other===button));root.querySelector('#record-status').textContent=state.label;root.querySelector('#record-status').className='badge'+(button.dataset.record==='due'?' bg-cream text-amber':'');root.querySelector('#record-date').textContent=state.date;root.querySelector('#record-action').textContent=state.action;root.querySelector('#record-history').textContent=state.history;root.querySelector('#record-announcement').textContent=state.label+'. Expiry '+state.date+'. '+state.action});
const sections=[...root.querySelectorAll('[data-chapter]')];if(sections.length){let pending=false;const handleScroll=()=>{if(pending)return;pending=true;requestAnimationFrame(()=>{const current=sections.filter(s=>s.getBoundingClientRect().top<=180).at(-1)||sections[0];for(const a of root.querySelectorAll('[data-chapter-link]')){if(a.dataset.chapterLink===current.id)a.setAttribute('aria-current','true');else a.removeAttribute('aria-current')}pending=false})};window.addEventListener('scroll',handleScroll,{passive:true,signal:controller.signal});handleScroll()}
const attendance=root.querySelector('#attendance-preview');attendance?.addEventListener('click',()=>{const checked=attendance.getAttribute('aria-pressed')!=='true';attendance.setAttribute('aria-pressed',String(checked));attendance.textContent=checked?'See the check-in record ←':'See the check-out record →';root.querySelector('#attendance-state').textContent=checked?'Check-out recorded':'On site now';root.querySelector('#checkout-time').textContent=checked?'16:31':'Not yet recorded';root.querySelector('#attendance-announcement').textContent=checked?'Jamie checked out at 16:31. The visit remains in the history.':'Jamie is on site. Check-in recorded at 08:02.'});

const gaps={missing:{person:'Riley Ellis',record:'Workplace induction',action:'Request the missing evidence.',detail:'Check the role requirement, then ask Riley to supply the induction record.'},due:{person:'Jamie Taylor',record:'Manual handling · Expires 30 Nov 2026',action:'Arrange the next renewal.',detail:'Check the expiry date and plan when Jamie needs to supply replacement evidence.'},review:{person:'Alex Morgan',record:'Training certificate',action:'Review the evidence supplied.',detail:'Open the certificate, compare it with the role requirement and record your review.'}};
for(const button of root.querySelectorAll('[data-gap]'))button.addEventListener('click',()=>{const value=gaps[button.dataset.gap];for(const b of root.querySelectorAll('[data-gap]'))b.setAttribute('aria-pressed',String(b===button));for(const key of ['person','record','action','detail'])root.querySelector('#gap-'+key).textContent=value[key];root.querySelector('#gap-announcement').textContent=value.person+'. '+value.action});
const owners={personal:{label:'Held by the person',title:'Manual handling certificate',copy:'Jamie keeps this personal credential in the app and shares the evidence needed for work.',review:'Review the shared evidence against the role’s requirements.'},company:{label:'Held by the company',title:'North site induction',copy:'Your organisation maintains the site induction and its review record in the company workspace.',review:'Maintain the company record and keep the review activity current.'}};
for(const button of root.querySelectorAll('[data-owner]'))button.addEventListener('click',()=>{const value=owners[button.dataset.owner];for(const b of root.querySelectorAll('[data-owner]'))b.setAttribute('aria-pressed',String(b===button));for(const key of ['label','title','copy','review'])root.querySelector('#owner-'+key).textContent=value[key];root.querySelector('#owner-announcement').textContent=value.label+'. '+value.title+'. '+value.copy});
const workload=root.querySelector('#workload');
function handleWorkload(){const tasks=workload.elements.tasks,minutes=workload.elements.minutes,output=root.querySelector('#workload-result'),formula=root.querySelector('#workload-formula');if(!tasks.validity.valid||!minutes.validity.valid){output.textContent='Check your inputs';formula.textContent='Enter whole numbers: 0 to 100,000 follow-ups and 0 to 1,440 minutes.';return}const hours=tasks.valueAsNumber*minutes.valueAsNumber/60;output.textContent=new Intl.NumberFormat('en-GB',{maximumFractionDigits:1}).format(hours)+(hours===1?' hour':' hours');formula.textContent=`${tasks.valueAsNumber.toLocaleString('en-GB')} follow-ups × ${minutes.valueAsNumber.toLocaleString('en-GB')} minutes ÷ 60`}
workload?.addEventListener('input',handleWorkload);workload?.addEventListener('submit',event=>{event.preventDefault();handleWorkload()});


return()=>controller.abort();}
